"""
Sentiment Analysis Page
Detailed analysis of sentiment dimensions and patterns
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from utils import get_sentiment_color, get_sentiment_label, data_source_badge

def calculate_sentiment_stats(df, dimension):
    """Calculate statistics for a given sentiment dimension"""
    return {
        'mean': df[dimension].mean(),
        'median': df[dimension].median(),
        'std': df[dimension].std(),
        'min': df[dimension].min(),
        'max': df[dimension].max(),
        'count': len(df)
    }

def render(filtered_df, full_df):
    """Render the Sentiment Analysis page"""
    
    st.header("🎯 Sentiment Analysis")
    st.markdown("**Deep dive into AI-analyzed customer sentiment across all dimensions**")
    st.caption(data_source_badge('ai_analysis'))
    
    # Explanation of metrics
    st.info("**AI Sentiment Analysis:** These scores (1-5) are generated by AI analysis of review text, measuring sentiment across 5 strategic dimensions. This is different from the Overall User Rating which is the reviewer's direct star rating.")
    
    # Display data scope indicator
    products_in_view = sorted(filtered_df['Product'].unique().tolist())
    if len(products_in_view) == 1 and products_in_view[0] == 'Dayforce':
        st.success(f"🎯 **Analyzing: Dayforce Only** - Enable 'Compare with Competitors' below to see competitive context")
    elif 'Dayforce' in products_in_view:
        st.info(f"📊 **Analyzing: {len(products_in_view)} Products** - Includes Dayforce + {len(products_in_view)-1} competitors")
    else:
        st.warning(f"⚠️ **Note:** Currently viewing competitors only (no Dayforce data). Adjust filters to include Dayforce.")
    
    dimensions = ['product', 'gtm', 'market_direction', 'implementation', 'customer_experience']
    dimension_labels = {
        'product': 'Product Capabilities (AI Sentiment)',
        'gtm': 'Go-to-Market (AI Sentiment)',
        'market_direction': 'Market Direction (AI Sentiment)',
        'implementation': 'Implementation (AI Sentiment)',
        'customer_experience': 'Customer Experience (AI Sentiment)'
    }
    
    # Dimension selector
    col1, col2 = st.columns([2, 1])
    
    with col1:
        selected_dimension = st.selectbox(
            "Select Dimension to Analyze",
            dimensions,
            format_func=lambda x: dimension_labels[x]
        )
    
    with col2:
        comparison_mode = st.checkbox("Compare with Competitors", value=True)
    
    st.markdown("---")
    
    # Main analysis section
    col_main, col_stats = st.columns([2, 1])
    
    with col_main:
        st.subheader(f"📊 {dimension_labels[selected_dimension]} Analysis")
        
        if comparison_mode:
            # Compare across products
            product_avg = filtered_df.groupby('Product')[selected_dimension].agg(['mean', 'count']).reset_index()
            product_avg = product_avg.sort_values('mean', ascending=False)
            
            # Create bar chart
            fig = px.bar(
                product_avg,
                x='Product',
                y='mean',
                title=f"{dimension_labels[selected_dimension]} by Product",
                labels={'mean': 'Average Score', 'Product': 'Product'},
                color='mean',
                color_continuous_scale='RdYlGn',
                range_color=[3, 5],
                text='mean'
            )
            
            fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
            fig.update_layout(
                yaxis=dict(range=[0, 5]),
                showlegend=False,
                height=400
            )
            
            st.plotly_chart(fig, use_container_width=True)
            
            # Show review counts
            st.caption("Review counts: " + ", ".join([f"{row['Product']}: {int(row['count'])}" for _, row in product_avg.iterrows()]))
        
        else:
            # Distribution for selected dimension
            fig = px.histogram(
                filtered_df,
                x=selected_dimension,
                title=f"Distribution of {dimension_labels[selected_dimension]} Scores",
                labels={selected_dimension: 'Score'},
                nbins=20,
                color_discrete_sequence=['#3498db']
            )
            
            # Add mean line
            mean_score = filtered_df[selected_dimension].mean()
            fig.add_vline(x=mean_score, line_dash="dash", line_color="red",
                         annotation_text=f"Mean: {mean_score:.2f}")
            
            fig.update_layout(height=400)
            st.plotly_chart(fig, use_container_width=True)
        
        # Time series analysis
        st.subheader("📈 Trend Over Time")
        
        trend_df = filtered_df.copy()
        trend_df['Month'] = trend_df['parsed_date'].dt.to_period('M').astype(str)
        
        if comparison_mode:
            # By product over time
            monthly_product = trend_df.groupby(['Month', 'Product'])[selected_dimension].mean().reset_index()
            
            fig = px.line(
                monthly_product,
                x='Month',
                y=selected_dimension,
                color='Product',
                title=f"{dimension_labels[selected_dimension]} Trend by Product",
                markers=True,
                labels={selected_dimension: 'Average Score'}
            )
        else:
            # Overall trend
            monthly_avg = trend_df.groupby('Month')[selected_dimension].mean().reset_index()
            
            fig = px.line(
                monthly_avg,
                x='Month',
                y=selected_dimension,
                title=f"{dimension_labels[selected_dimension]} Trend",
                markers=True,
                labels={selected_dimension: 'Average Score'}
            )
            
            fig.update_traces(line=dict(width=3), marker=dict(size=10))
        
        fig.update_layout(
            yaxis=dict(range=[2.5, 5.5]),
            height=350
        )
        
        st.plotly_chart(fig, use_container_width=True)
    
    with col_stats:
        st.subheader("📈 Statistics")
        
        # Overall stats
        stats = calculate_sentiment_stats(filtered_df, selected_dimension)
        
        st.metric("Avg AI Sentiment", f"{stats['mean']:.2f}")
        st.metric("Median AI Sentiment", f"{stats['median']:.2f}")
        st.metric("Std Deviation", f"{stats['std']:.2f}")
        
        st.markdown("---")
        
        st.markdown(f"**Score Range**")
        st.markdown(f"Min: {stats['min']:.2f}")
        st.markdown(f"Max: {stats['max']:.2f}")
        st.markdown(f"Reviews: {stats['count']}")
        
        st.markdown("---")
        
        # Score distribution
        st.markdown("**Score Distribution**")
        score_ranges = {
            '5.0 (Excellent)': len(filtered_df[filtered_df[selected_dimension] == 5]),
            '4.0-4.9 (Good)': len(filtered_df[(filtered_df[selected_dimension] >= 4) & (filtered_df[selected_dimension] < 5)]),
            '3.0-3.9 (Average)': len(filtered_df[(filtered_df[selected_dimension] >= 3) & (filtered_df[selected_dimension] < 4)]),
            'Below 3.0 (Poor)': len(filtered_df[filtered_df[selected_dimension] < 3])
        }
        
        for range_label, count in score_ranges.items():
            pct = (count / len(filtered_df) * 100) if len(filtered_df) > 0 else 0
            st.markdown(f"{range_label}: **{count}** ({pct:.1f}%)")
    
    st.markdown("---")
    
    # Correlation matrix
    st.subheader("🔗 Dimension Correlations")
    st.markdown("*How do the different dimensions relate to each other?*")
    
    with st.expander("ℹ️ How to Read This Chart"):
        st.markdown("""
        **Correlation Coefficient** measures the statistical relationship between two dimensions, ranging from -1 to +1:
        
        - **+1.0 (Deep Red)**: Perfect positive correlation - when one dimension's score increases, the other always increases by the same proportion
        - **+0.7 to +1.0 (Red)**: Strong positive correlation - dimensions tend to move together
        - **+0.3 to +0.7 (Light Red)**: Moderate positive correlation - some relationship exists
        - **-0.3 to +0.3 (White)**: Weak or no correlation - dimensions are relatively independent
        - **-0.7 to -0.3 (Light Blue)**: Moderate negative correlation - dimensions tend to move in opposite directions
        - **-1.0 to -0.7 (Blue)**: Strong negative correlation - when one increases, the other tends to decrease
        - **-1.0 (Deep Blue)**: Perfect negative correlation - dimensions always move in opposite directions
        
        **What This Means:**
        - **High positive correlations** suggest dimensions are interconnected (e.g., good product quality often comes with good customer experience)
        - **Low correlations** suggest dimensions are independent areas that can be improved separately
        - **Negative correlations** (rare) might indicate trade-offs between dimensions
        
        **Calculation:** Uses Pearson correlation coefficient computed across all reviews in the current selection.
        """)
    
    corr_matrix = filtered_df[dimensions].corr()
    
    fig = px.imshow(
        corr_matrix,
        labels=dict(color="Correlation"),
        x=[dimension_labels[d] for d in dimensions],
        y=[dimension_labels[d] for d in dimensions],
        color_continuous_scale='RdBu',  # Red for positive, Blue for negative
        aspect="auto",
        zmin=-1,
        zmax=1
    )
    
    fig.update_layout(height=400)
    st.plotly_chart(fig, use_container_width=True)
    
    st.markdown("---")
    
    # Detailed reviews table
    st.subheader("🔍 Review Details")
    
    # Filter options
    col_f1, col_f2 = st.columns(2)
    
    with col_f1:
        score_filter = st.select_slider(
            "Filter by Score",
            options=['All', '5.0', '4.0-4.9', '3.0-3.9', 'Below 3.0'],
            value='All'
        )
    
    with col_f2:
        sort_order = st.selectbox(
            "Sort by",
            ['Highest Score', 'Lowest Score', 'Most Recent']
        )
    
    # Apply filters
    display_df = filtered_df.copy()
    
    if score_filter == '5.0':
        display_df = display_df[display_df[selected_dimension] == 5]
    elif score_filter == '4.0-4.9':
        display_df = display_df[(display_df[selected_dimension] >= 4) & (display_df[selected_dimension] < 5)]
    elif score_filter == '3.0-3.9':
        display_df = display_df[(display_df[selected_dimension] >= 3) & (display_df[selected_dimension] < 4)]
    elif score_filter == 'Below 3.0':
        display_df = display_df[display_df[selected_dimension] < 3]
    
    # Sort
    if sort_order == 'Highest Score':
        display_df = display_df.sort_values(selected_dimension, ascending=False)
    elif sort_order == 'Lowest Score':
        display_df = display_df.sort_values(selected_dimension, ascending=True)
    else:  # Most Recent
        display_df = display_df.sort_values('parsed_date', ascending=False)
    
    # Display table
    for idx, row in display_df.head(10).iterrows():
        score = row[selected_dimension]
        color = get_sentiment_color(score)
        
        with st.expander(f"**{row['Product']}** - Score: {score} - {row['Review Date']}"):
            st.markdown(f"**Headline:** {row['Headline']}")
            st.markdown(f"**Overall Rating (Reviewer):** {row['Overall User Rating']}/5")
            st.markdown(f"**Reviewer:** {row['Reviewer Role ']} | {row['Reviewer Industry']} | {row['Reviewer Firm Size']}")
            st.markdown("---")
            st.markdown("**Overall Comment:**")
            st.markdown(row['Overall Comment'])
            
            if pd.notna(row['Lessons Learned']):
                st.markdown("---")
                st.markdown("**Lessons Learned:**")
                st.markdown(row['Lessons Learned'])
